version: '3'
services:
  test-checker:
    build: .
    ports:
      - 3031:3031
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
  mongo:
    image: mongo
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
