trigger:
  tags:
    include:
      - v*
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'

- script: 'pip3 install twine wheel'

- task: TwineAuthenticate@1
  inputs:
    pythonUploadServiceConnection: 'pypi_enowars'

- script: python3 setup.py sdist bdist_wheel

- script: 'python3 -m twine upload -r "pypi_enowars" --config-file $(PYPIRC_PATH) dist/*'
