# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: 'pip3 install twine'
- task: TwineAuthenticate@0
  inputs:
    externalFeeds: 'pypi_enochecker_async'
- script: python3 setup.py install --user
