trigger:
- refs/tags/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: 'pip3 install twine wheel'
- task: TwineAuthenticate@0
  inputs:
    externalFeeds: 'pypi_enochecker_async'
- script: python3 setup.py sdist bdist_wheel
- script: 'python3 -m twine upload -r enochecker_async --config-file $(PYPIRC_PATH) dist/*'
